apiVersion: batch/v1
kind: Job
metadata:
  name: istio-demo-install
  labels:
    app: istio-demo
spec:
  template:
    spec:
      containers:
        - name: istio-demo-installer
          image: docker.io/istio/install-cni:1.10.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              /usr/local/bin/istioctl install --set profile=demo -f /etc/istio/values.yaml
      restartPolicy: Never