apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: {{ .Release.Name }}-test
  namespace: {{ .Release.Namespace }}
spec:
  profile: demo
  components:
    ingressGateways:
      - enabled: true
        namespace: istio-system