apiVersion: v2
name: istio
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

dependencies:
  - name: base
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.18.2
  - name: istiod
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.18.2
  - name: gateway
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.18.2
