microservices:
  - name: kiali
    port: 20001
  - name: grafana
    port: 3000
  - name: prometheus
    port: 432
  - name: jaeger
    port: 16686

istio:
  enabled: true
  grafana:
    enabled: true
  kiali:
    enabled: true